SELECT * FROM ROOM;
SELECT * FROM CHAT;

DROP TABLE ROOM CASCADE CONSTRAINTS;
DROP SEQUENCE ROOM_SEQ;
DROP TABLE CHAT CASCADE CONSTRAINTS;
DROP SEQUENCE CHAT_SEQ;

CREATE TABLE ROOM (
	room_id	NUMBER NOT NULL	PRIMARY KEY,
	room_name VARCHAR2(50) NOT NULL
);
CREATE SEQUENCE ROOM_SEQ;

CREATE TABLE CHAT (
	chat_id	NUMBER NOT NULL	PRIMARY KEY,
	room_id NUMBER NOT NULL,
	writer VARCHAR2(30) NOT NULL,
	msg CLOB,
	
	CONSTRAINT fk_room_id FOREIGN KEY (room_id) REFERENCES ROOM(room_id)
);
CREATE SEQUENCE CHAT_SEQ;